---
# Traefik Dashboard Certificate
# Automatically issued by cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: traefik-dashboard-tls
  issuerRef:
    name: {{ .Values.services.traefik.cert_issuer | default .Values.global.cert_issuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.services.traefik.domain }}

