---
# Grafana TLS Certificate
# Automatically issued by cert-manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: grafana-tls
  issuerRef:
    name: {{ .Values.services.grafana.cert_issuer | default .Values.global.cert_issuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.services.grafana.domain }}

