---
# Grafana IngressRoute
# Access at: https://{{ .Values.services.grafana.domain }}
# Protected by Authelia SSO
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.services.grafana.domain }}`)
      kind: Rule
      middlewares:
        - name: authelia-forward-auth
          namespace: authelia
      services:
        - name: grafana
          port: 80
  tls:
    secretName: grafana-tls
