---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: {{ .Values.global.cert_issuer | default "letsencrypt-prod" }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Release.Name }}.{{ .Values.global.domain }}
  privateKey:
    algorithm: ECDSA
    size: 256
