---
# TLS Certificate for MinIO Console
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-console-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: minio-console-tls
  issuerRef:
    name: {{ .Values.global.cert_issuer | default "letsencrypt-prod" }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.services.minio.console_domain | default "minio-console.silverseekers.org" }}

