# Default values for MinIO Console
# These are overridden by config/homelab.yaml when deploying

global:
  domain: silverseekers.org
  cert_issuer: letsencrypt-prod

services:
  minio_console:
    domain: s3-ui.silverseekers.org
  garage:
    domain: s3.silverseekers.org

