---
# Handlers for K3s Role
# These handlers are triggered by notify directives in tasks

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted


