---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-mcp-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgA5WGYg8B6FMIcu/ZtIJKdMEDSMKE3n/uNRMur2BbTUt0NIh7kTX2vktPsF3L9vVOLHqG8uwbNk0Y3/O1FzHVz1cjaT4ds01HNQyo5SH0rRWx/O5D3McJaWJFLsBUZvTGPwFV5yNSZslRIiqU8rR+mZ3fUISfx8w5M/nf1LFeDOc4FVR4HuVSwOtUGrviynh4B/IMukwWEY+0QVL2wZP/qHj5Vb3nb/ZX6dCyda7lDFsgO9PnQMlDEzV+IApqHWXmlPuTAPfScBv/h/serO6Qiqlza7vETMkqwts6UorZoZ53R3kbZf4XjCG4Ki2p3LW+/H7zOQckMrP11TxdvU6rm1zYFAAatisNgQveLKxBDltus2NCDsAIStaKneHKXSP3cy19GLBr6nEJ57P9sZwpYhH2oVi87/gJNAUVncxe4UIJAdE5rC4XG9BGad7uxCgq1m1NKnIbSC5QTShEZcna7Lg7xtbuu6uyk39yCmFoOzAGMWPw/c9IVA/JlCHCu37Hb3u0ikkGTu4f2iiqXaTDpK44qbfurCftQAhMktqXwaniYkvCRvUznEXik8uilKaLmJIufoKiBp07l1JIykvxtaFl5/k03xWavf6n6i9k6rRe0OuKiqhjNP+Xhsr7gjGRoeVAHD0nM/wetfVYaSMxhdj0ZYU3uodszZiW+F5G0CZQKrGZXFbPTQnX/EUi4mGSSJxxu0hb+nb9jax/Q1sgh1LX8N+/YrNb80c0RZa7RzE5zRSEqgLbbZrOGnj9aAZxbGcQcsBk0GulE8bh26S8Bv8g==
  template:
    metadata:
      name: grafana-mcp-token
      namespace: monitoring
